installStatePath: .yarn/install-state.gz

logFilters:
  - level: discard
    pattern: "* with version 0.0.1-generated-at-build, which doesn't satisfy what *"

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
